"""empty message

Revision ID: 114909e05e99
Revises: 
Create Date: 2022-04-04 17:50:00.632601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114909e05e99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='guilds_pkey')
                    )
    op.create_table('channels',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('mirror_to_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('janitor_limit', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('janitor_frequency', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('janitor_init_wipe', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name='channels_guild_id_fkey'),
                    sa.ForeignKeyConstraint(['mirror_to_channel_id'], ['channels.id'],
                                            name='channels_mirror_to_channel_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='channels_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    op.drop_table('channels')
    # ### end Alembic commands ###
