# docker compose up
# hostname: host.docker.internal OR localhost
# port: 5432
# user: postgres
# password: admin
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"